### PR TITLE
Changed all Vec2 to (hardware accelerated) System.Numerics.Vector2

### PR DESCRIPTION
**Pull request by Kira-PH**
It would be good to get some unit tests around this. Seems to work with a basic test harness to bounce objects off surfaces.

### CODE REVIEW

**Comment by Kira-PH** [comment]
Works with the existing Console HelloWorld and Window tests too

I recognise this represents "not-insignificant" changes to the API. I have cleaned up Vec2 so that it only holds X and Y and has no other functions. We could add Obsolete-marked stub methods that support the current API. WDYT?

**Comment by codingben** [comment]
> It would be good to get some unit tests around this. Seems to work with a basic test harness to bounce objects off surfaces.

We'll see. I wanted to do unit tests for this library.

> Works with the existing Console HelloWorld and Window tests too
> 
> I recognise this represents "not-insignificant" changes to the API. I have cleaned up Vec2 so that it only holds X and Y and has no other functions. We could add Obsolete-marked stub methods that support the current API. WDYT?

Thanks! Looks good. I think it's okay. Not added yet? Tomorrow I'll merge your PR and create a new version of the package.

**Comment by Kira-PH** [comment]
Don't add it yet, I'll add the legacy API support first - otherwise some people might get upset. (Also you won't be able to use it in maple-fighters without changes to your code)

**Comment by Kira-PH** [comment]
I didn't do much API compatibility stuff because Vec2 will already implicitly cast to Vector2 and vice versa. The biggest issue will be anything that pulls arrays out of Box2D. I've changed DebugDraw to automatically convert to Vec2[] but we should probably update that in a later version. Since there are so many changes - despite the retained compatibility - the next package version should probably get a major version increment.
I've made stacks more changes, including ditching Box2DXDebug and swapping out Math calls to Framework calls
Works fine with WindowTests, but WindowTests is now flickery (might be something odd here - I'm running Ubuntu)
I would ask that you try it with anything else you have as a sanity check.

**Comment by Kira-PH** [comment]
I've got some odd behaviour I want to check out before committing.

**Comment by Kira-PH** [comment]
Checked out odd behaviour, it exists in your master branch too.

**Comment by codingben** [comment]
> I didn't do much API compatibility stuff because Vec2 will already implicitly cast to Vector2 and vice versa. The biggest issue will be anything that pulls arrays out of Box2D. I've changed DebugDraw to automatically convert to Vec2[] but we should probably update that in a later version. Since there are so many changes - despite the retained compatibility - the next package version should probably get a major version increment.
> I've made stacks more changes, including ditching Box2DXDebug and swapping out Math calls to Framework calls
> Works fine with WindowTests, but WindowTests is now flickery (might be something odd here - I'm running Ubuntu)
> I would ask that you try it with anything else you have as a sanity check.

Thanks man! great work. I pushed a fix for window tests. I had to run tests several times to understand what was wrong, because I couldn't see the problem.

Please let me know if it works now without flickering and if we ready to merge PR (I'll check your code again before merge PR).

**Comment by Kira-PH** [comment]
Will do. I wanted to use WheelJoint but this cut is about 12 years out of date compared to Box2D, so I've also been updating it... (Not in this branch - just local commits for now)

**Comment by Kira-PH** [comment]
If you're unsure about AggressiveInlining that I added to some methods, check this out...

https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABABgAJiBGAOgCUBXAOwwEt8YaBhCfAB1YAbGFADKIgG6swMXAG4AsAChiAZkoAmcl3IBvZeUPk+UVhOwYY5Vi3IBBPQaPOA2gFkYGABYQAJgEl+QQAKD28/QL5BAHk+NggmXBoAOQh/JkEbGwBzAEoAXSMnZ0Nsz3IAXgA+cio5cgBfYpLmkzMLKxsMcgAhRyUSo3dPHwCg0JGIoNj4xJo7bOzYXFwzGHTMphyCooHB8jLu6trFPcMms/JmtUoUcgB1U0s7YNz9S5LqGmoATmC7XL1QzNC7Oa7qYh3R6sSw9V7vfaGL6/YI9QEg5QNIA=

**Comment by codingben** [comment]
> Will do. I wanted to use WheelJoint but this cut is about 12 years out of date compared to Box2D, so I've also been updating it... (Not in this branch - just local commits for now)

Yes, I think this is because mostly people prefer to use C++. I just need this Box2D to simulate physics for server-side enemies... with support for the latest versions of .NET.

> If you're unsure about AggressiveInlining that I added to some methods, check this out...
> 
> https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABABgAJiBGAOgCUBXAOwwEt8YaBhCfAB1YAbGFADKIgG6swMXAG4AsAChiAZkoAmcl3IBvZeUPk+UVhOwYY5Vi3IBBPQaPOA2gFkYGABYQAJgEl+QQAKD28/QL5BAHk+NggmXBoAOQh/JkEbGwBzAEoAXSMnZ0Nsz3IAXgA+cio5cgBfYpLmkzMLKxsMcgAhRyUSo3dPHwCg0JGIoNj4xJo7bOzYXFwzGHTMphyCooHB8jLu6trFPcMms/JmtUoUcgB1U0s7YNz9S5LqGmoATmC7XL1QzNC7Oa7qYh3R6sSw9V7vfaGL6/YI9QEg5QNIA=

Cool, I see that instead of calling a method, it takes a value directly, right? It seems like an optimization process.

**Comment by Kira-PH** [comment]
I think mostly people prefer to use heavyweight frameworks like Godot Engine, Unity, etc. many of which use C#. I think you might be surprised how much stuff uses C#.

Regarding inlining - yes, but it's not limited to properties and values. It will move all the code to the call site, eliminating the call completely. The default is for the JIT compiler to work it out, so where I added "NoInlining" it was really to force the point of what happens when the compiler chooses not to inline. AggressiveInlining expresses intent to the compiler. For longer methods with more locals, it might be more efficient not to inline, and the JIT compiler will change the way the call is made in realtime even if you've expressed the AggressiveInlining intent.

Looking at Erin' C++ code, there are plenty of "inline" methods in the header files, which the compiler will turn into direct calls. You could consider the C++ Compiler to be more "obedient".

In general, there is no point in considering such optimisations. Very few web sites would gain any tangible benefit from them, and since time is money, developers generally don't need to worry about it. But for 'special cases' like Box2D, or in business systems where GPU is not an option, this sort of optimisation is useful. (And actually it becomes more useful when using Cloud compute resource and when the optimisation saves paid-for execution time. The question is whether it costs more to pay the developers to understand and implement it, or to let it run unoptimised.)

**Comment by Kira-PH** [comment]
I have (finally) got this almost up-to-date with Box2D, just need to add chain shapes (and their collisions) and some joints. That does mean there are more changes to implement this version.

Do you want the updated version? If so, I would recommend giving it a version like 2.0-alpha. I intend to change a lot of the namespaces and remove the Box2DX name (because it is no longer that)

**Comment by codingben** [comment]
> I think mostly people prefer to use heavyweight frameworks like Godot Engine, Unity, etc. many of which use C#. I think you might be surprised how much stuff uses C#.
> 
> Regarding inlining - yes, but it's not limited to properties and values. It will move all the code to the call site, eliminating the call completely. The default is for the JIT compiler to work it out, so where I added "NoInlining" it was really to force the point of what happens when the compiler chooses not to inline. AggressiveInlining expresses intent to the compiler. For longer methods with more locals, it might be more efficient not to inline, and the JIT compiler will change the way the call is made in realtime even if you've expressed the AggressiveInlining intent.
> 
> Looking at Erin' C++ code, there are plenty of "inline" methods in the header files, which the compiler will turn into direct calls. You could consider the C++ Compiler to be more "obedient".
> 
> In general, there is no point in considering such optimisations. Very few web sites would gain any tangible benefit from them, and since time is money, developers generally don't need to worry about it. But for 'special cases' like Box2D, or in business systems where GPU is not an option, this sort of optimisation is useful. (And actually it becomes more useful when using Cloud compute resource and when the optimisation saves paid-for execution time. The question is whether it costs more to pay the developers to understand and implement it, or to let it run unoptimised.)

Great explanation. Thanks!

If we are talking about cloud computing, .NET will require a lot more memory (and probably a processor) compared to other technologies like Go. I'm right? (I know that Go will take up very little standby memory)

And that is why C++ is preferable for really difficult tasks (for example, physics, etc.)

> I have (finally) got this almost up-to-date with Box2D, just need to add chain shapes (and their collisions) and some joints. That does mean there are more changes to implement this version.
> 
> Do you want the updated version? If so, I would recommend giving it a version like 2.0-alpha. I intend to change a lot of the namespaces and remove the Box2DX name (because it is no longer that)

Yes, of course, we'll do version 2.0.0. Do whatever you want and don't forget to add credit for your hard work! :)

Feel free to change README and everything you would like to do.

**Comment by Kira-PH** [comment]
Wow, BIG changes...
image

Main points: Mostly up-to-date. I have bumped the version numbers up, updated LICENSE and NuGet package info (credit to us as well as Erin), separated every class/struct to its own file, applied license headers to all the files. Also took a copy of Erin's documentation and changed all the examples to C# and Vector2. I'll contact Chris Campbell (iforce2d.net) and see if we can link to his tutorials and RUBE app.

Todo: ChainShape, FrictionJoint, MotorJoint, WeldJoint, WheelJoint, Rope

**Comment by Kira-PH** [comment]
> If we are talking about cloud computing, .NET will require a lot more memory (and probably a processor) compared to other technologies like Go. I'm right?

Not necessarily. .NET can do just as much fancy fast access memory stuff as can be done with C++. You can use pointers etc (as you know) and there are "hardware intrinsics" in .NET Core 3.0 onwards: https://devblogs.microsoft.com/dotnet/hardware-intrinsics-in-net-core/

In addition, memory is cheap - and .NET doesn't really use all that much. For example, the smallest machine I can get on, e.g. Amazon, has 512MB RAM. We have been developing a "Travelling Salesman" algorithm where I work and for 300 sites and several vehicles, it uses about 100MB of RAM.

C# has the advantage of being very accessible and very familiar while also being very powerful. .NET has the advantage of Just In Time compilation. While JIT will slow the initial load time (because it has to do an additional compile), it will also make use of the hardware features that are available.

What we see in SharpLab.io is the actual machine code as it would be executed - and we can see that even for a simple for loop over an array of floats, it will use AVX-512 to accelerate the function:
https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgGYACAbwFgAoSpys0mh5zygMwBsJsGANoBdHv0G5KAXkoA7GAHdxA4ShEBuDlybdoACgCWcjJUPSADBrMAeFNcMBqRwEo6jHVz6rcQwyMdpQy0PHQBfbSYI+jCgA==

In the right hand pane you will see the following CPU instructions: movsxd, vxorps, vcvtsi2ss, vaddss, vmovss. These are AVX instructions, e.g.
https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=vcvtsi2ss&expand=1321

**Comment by codingben** [comment]
> Wow, BIG changes...
> image
> 
> Main points: Mostly up-to-date. I have bumped the version numbers up, updated LICENSE and NuGet package info (credit to us as well as Erin), separated every class/struct to its own file, applied license headers to all the files. Also took a copy of Erin's documentation and changed all the examples to C# and Vector2. I'll contact Chris Campbell (iforce2d.net) and see if we can link to his tutorials and RUBE app.
> 
> Todo: ChainShape, FrictionJoint, MotorJoint, WeldJoint, WheelJoint, Rope

I'll review your changes and make a new package tomorrow. I'll keep you up to date.

**Pull request merged**
