### PR TITLE
[Work in Progress] Failing Unit Test

### PR DESCRIPTION
**Pull request by TinkerWorX**
This PR contains a failing unit test where a body moves through another without affecting it.

The unit test is an absolute mess, but it's the only reproducible setup I have managed to create.

If we figure out the cause of the issue, we can likely distill a cleaner unit test and just drop this PR.

### CODE REVIEW

**Comment by TinkerWorX** [comment]
Here is an example of what the scene does.
ezgif-2-02a261341ceb
There are a lot of bodies outside the view, but this is the only way to show the issue reliably.

**Comment by codingben** [comment]
@TinkerWorX Hi man, thank you for your contribution. Please let me know when your PR is ready and I'll review it (I see WIP).

**Comment by TinkerWorX** [comment]
@benukhanov I made the unit test as requested by @HughPH so I think he'll try and guide me on how to find what's causing the issue. Afterwards, we can turn this into a cleaner unit test and merge it.

**Comment by codingben** [comment]
@TinkerWorX Sounds good. 😄

**Comment by Kira-PH** [comment]
Sorry, I didn't notice this for some reason. Gmail probably put the notification in my SPAM. I do remember the problem. I'll try to get to it this week.

**Comment by Kira-PH** [comment]
Hi, I found some time to look into this - _eventually!_. The problem is that you have two (or more) shapes at the exact same position (21, 103) and this causes the DynamicTree to fail: the NaN created by trying to Normalize the Vector (0,0) permeates through the code and causes chaos. The Tree gets AABBs that are NaN-sized, and so it becomes impossible to find overlapping AABBs.

It can be "fixed" with the same code as in this PR: https://github.com/codingben/box2d-netstandard/pull/43

You have two choices: Implement the fix in your own fork of Box2D, or make sure never to put two asteroids at the same position. Adding a random floating point value between 0.001 and 0.002 would probably suffice, if you're sensitive to asteroids sitting on integer boundaries. They only need to be different by Float.Epsilon (which is smaller than Settings.FLT_EPSILON).

I don't want to implement the change in Box2D because it's something that doesn't happen outside of the time at which you create the World or - potentially - if you added a 2nd body to a running World with the same position as an existing body. In either case, you have to do something to break it, and so it won't happen during the potentially billions of iterations that don't fall into either of those categories.

**Pull request closed without merging**
