### PR TITLE
Nothing major here

### PR DESCRIPTION
**Pull request by Kira-PH**
The RubeGoldberg test works fine in Release mode with no debugger but behaves differently otherwise. On Linux I have three different behaviours:
1. Debugger not attached, Debug build / DEBUG Defined
2. Debugger not attached, Release build / DEBUG Not Defined
3. Debugger attached, regardless of build / DEBUG state

Added PolyEdgeTest because I was trying to figure out why poly/edge collisions weren't working.

Commented out all Debug.Assert lines - although this hasn't prevented having 3 different behaviours.
Updated RubeGoldberg to have edges as intended.
Added step-by-step mode to SimulationWindow

### CODE REVIEW

**Comment by codingben** [comment]
@HughPH Hey!

The RubeGoldberg test works, but when the ball hits the box, it stops to move on.. Can we use gyazo to make sure we are on the same page?

**Comment by codingben** [comment]
> @HughPH Hey!
> 
> The RubeGoldberg test works, but when the ball hits the box, it stops to move on.. Can we use gyazo to make sure we are on the same page?


https://gyazo.com/e4af9258264b3731d323f677860ee4d9

**Comment by codingben** [comment]
We'll make a new version of the package after this PR has merged, right?

What do you think about moving the TestWorlds folder to the ./examples or ./tests folder?

I took off yesterday and saw that you made several PR and merged. I didn't see them, so if I need to, let me know if in case I missed something.

Thank you very much for your hard work. Great contribution to this project man! :)

**Comment by Kira-PH** [comment]
So the thing with all of this is that it seems to give different results depending on whether you're running it in debug or release mode, and whether or not you have the debugger attached.
If the debugger is attached, regardless of whether DEBUG is defined, it always works the same.
Otherwise it works differently again when it's a Debug build (DEBUG defined, no optimisation) and when it's a Release build.

I suspect the differences are because of the high performance AVX instructions, and the reordering of instructions that happens in the optimised code.

**Comment by Kira-PH** [comment]
It should look something like this (choppiness is because of the screen recorder that I used)
The fact you have a blue background suggests you don't have the newest code :)

Peek 2020-06-23 23-18

**Comment by Kira-PH** [comment]
I don't mind where files go, so long as everything builds. There are a couple of unit tests now. One which runs this scene for 30 (imaginary) seconds (takes ~5 real seconds on my 5 year old laptop) and tests all the dynamic body positions, and one which I created because I had odd behaviour in another application I'm writing, and wanted to make sure it wasn't Box2D at fault. We already have 56% code coverage!

I tried a Debug build with optimisation enabled, and it works like above unless the debugger is attached.

**Comment by Kira-PH** [comment]
An additional note: Profiling shows that Box2D spends most of its time in TimeOfImpact()

**Comment by Kira-PH** [comment]
> We'll make a new version of the package after this PR has merged, right?

Yes, that sounds good. Make sure it's a Release build with optimisation enabled. Still alpha until the stretching joint problem is solved, I think.

**Comment by codingben** [comment]
> > We'll make a new version of the package after this PR has merged, right?
> 
> Yes, that sounds good. Make sure it's a Release build with optimisation enabled. Still alpha until the stretching joint problem is solved, I think.

How to make sure that this is a release version with optimization enabled? I'm doing this command: "dotnet build -c release"

**Comment by codingben** [comment]
By the way, the version will be 2.0.1-alpha or 2.1.0-alpha?

**Comment by codingben** [comment]
I think we also need a new version of this package: https://www.nuget.org/packages/Box2D.Window/

WDYT, 1.0.0-alpha 2.0.0-alpha?

**Comment by Kira-PH** [comment]
> > > We'll make a new version of the package after this PR has merged, right?
> > 
> > 
> > Yes, that sounds good. Make sure it's a Release build with optimisation enabled. Still alpha until the stretching joint problem is solved, I think.
> 
> How to make sure that this is a release version with optimization enabled? I'm doing this command: "dotnet build -c release"

https://github.com/benzuk/box2d-netstandard/packages

I would make this 2.0.1-alpha

In my opinion it's not necessary to release Box2D.Window as a package, it will be fine as an example implementation used by Box2D.WindowTests. There are much bigger and better frameworks for dealing with windows, and this has a dependency on OpenTK which not everyone will want to use. If you want to make it bigger and better, it might be worth doing. Just my opinion, it's your package!

**Comment by codingben** [comment]
> > > > We'll make a new version of the package after this PR has merged, right?
> > > 
> > > 
> > > Yes, that sounds good. Make sure it's a Release build with optimisation enabled. Still alpha until the stretching joint problem is solved, I think.
> > 
> > 
> > How to make sure that this is a release version with optimization enabled? I'm doing this command: "dotnet build -c release"
> 
> https://github.com/benzuk/box2d-netstandard/packages
> 
> I would make this 2.0.1-alpha
> 
> In my opinion it's not necessary to release Box2D.Window as a package, it will be fine as an example implementation used by Box2D.WindowTests. There are much bigger and better frameworks for dealing with windows, and this has a dependency on OpenTK which not everyone will want to use. If you want to make it bigger and better, it might be worth doing. Just my opinion, it's your package!

Pushed: https://www.nuget.org/packages/Box2D.NetStandard/2.0.1-alpha

Good opinion, thanks. It's a good idea to rename this package to Box2D.OpenTkWindow. I need this package for my server project in order to be able to run the simulation window without re-writing the same code.

I have to say that you are a very professional guy. You did an excellent job here with your input. Many thanks. :)

**Comment by codingben** [comment]
Sorry for the delay, by the way. I have to go all day to military service, and then I have several hours of free time for training and working on my projects.

**Comment by Kira-PH** [comment]
> Good opinion, thanks. It's a good idea to rename this package to Box2D.OpenTkWindow. I need this package for my server project in order to be able to run the simulation window without re-writing the same code.

You don't need to publish it to be able to use it. You can build it, then add a reference to the assembly directly. Or you can include the project in your other solution and create a Project Reference.

**Pull request merged**
